site_name: Project Docs
site_description: Documentation for a project
site_url: https://Anatrax.github.io/
repo_url: https://github.com/Anatrax/MkDocsSetup
copyright: ©2020. Villegas, Samuel D.
site_dir: build
use_directory_urls: False
dev_addr: localhost:8000
theme: readthedocs
plugins:
    - search
#     - mkpdfs:
#         toc_position: none
#         author: Samuel D. Villegas
#         output_path: ../build/documentation.pdf
#         design: pdf-styles/style.css
nav:
    - 'Chapter 0': index.md
    - 'Chapter 1': Latches_and_Flip-Flops.md
    - 'Chapter 2': Arithmetic_and_Logic.md
