// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Sun Dec 20 21:42:22 2020

FullAdder FullAdder_inst
(
	.Cin(Cin_sig) ,	// input  Cin_sig
	.A(A_sig) ,	// input  A_sig
	.B(B_sig) ,	// input  B_sig
	.Cout(Cout_sig) ,	// output  Cout_sig
	.Z(Z_sig) 	// output  Z_sig
);

